# k8s/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
  namespace: default # Or your target namespace
  labels:
    app: backend-app
spec:
  replicas: 2 # Start with 2, can be adjusted
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app-container
        image: 811492260998.dkr.ecr.ap-southeast-1.amazonaws.com/bndz/backend:latest
        ports:
        - containerPort: 3000 # Port your backend Node.js app listens on
---
# k8s/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
  namespace: default # Or your target namespace
spec:
  selector:
    app: backend-app
  ports:
  - protocol: TCP
    port: 80 # Port the service will listen on internally in the cluster
    targetPort: 3000 # Port on the backend pods
  type: ClusterIP # Exposes the service on an internal IP in the cluster        